### ISSUE TITLE
命名規則（アンダースコア）はやめとこう

### ISSUE THREAD

**Issue by satocchi0416sh** [himura-shitara/suika-game-3d#33]
as is: アンダースコア
---------------------------------------
https://github.com/himura-shitara/suika-game-3d/blob/03e607ee1976e2be00d98fdc75944842fdd637c5/SuikaGame3D/Assets/Scripts/FruitMove.cs#L8-L10

to be: なしで統一
---------------------------------
```
private GameObject fruit;
private Rigidbody fruitRigidbody;
```

**Comment by himura-shitara** [comment]
研修生のみんななら分かる。耐え
