### ISSUE TITLE
GameOverChecker.csのprivate変数の命名

### ISSUE THREAD

**Issue by satocchi0416sh** [himura-shitara/suika-game-3d#34]
as is: アンダースコアついてる
---------------------------------------
https://github.com/himura-shitara/suika-game-3d/blob/03e607ee1976e2be00d98fdc75944842fdd637c5/SuikaGame3D/Assets/Scripts/GameOverChecker.cs#L6-L10

to be: なしで統一
---------------------------------
```
private bool isFruitColliding;
private float collisionTimer = 0f;
private const float GameOverTime = 4f;
```

**Comment by himura-shitara** [comment]
研修生のみんななら分かる。耐え
